FROM nodered/node-red-docker:rpi

RUN [ "cross-build-start" ]

RUN npm install node-red-contrib-openhab2
RUN npm install node-red-contrib-mqtt-broker
RUN npm install node-red-contrib-ros
RUN npm install node-red-contrib-image-output 

RUN [ "cross-build-end" ]
